@host = http://localhost:5048
@hostProd = https://prueba-marvel-back-dhb9cbhkc5g4ftfq.canadacentral-01.azurewebsites.net

# Iniciar sesión
POST {{hostProd}}/api/auth/login/
Accept: application/json
Content-Type: application/json

{
    "email": "guille@gmail.com",
    "password": "12345"
}

###

# Registrar usuario
POST {{host}}/api/auth/register/
Accept: application/json
Content-Type: application/json

{
    "nombre": "Guillermo Agudelo",
    "identificacion": "1122334455",
    "email": "guille9@gmail.com",
    "password": "12345",
    "confirmarPassword": "12345"
}

###

# Obtener comics desde Marvel
GET {{host}}/api/comic


###

# Obtener favoritos
GET {{host}}/api/favorite?email=guille1@gmail.com

###

# Agrega favorito
POST {{host}}/api/favorite
Content-Type: application/json

{
    "email": "guille1@gmail.com",
    "comicId": 2088
}

###

# Eliminar favorito
DELETE {{host}}/api/favorite
Content-Type: application/json

{
    "email": "guille1@gmail.com",
    "comicId": 331
}